[package]
name = "ci"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
quic = []

[dependencies]
xshell = "0.2"